<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2027.0.2-preview</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2027.0.2-preview</MetalamaVersion>
    <MetalamaPremiumVersion Condition="'$(MetalamaPremiumVersion)' == ''">2027.0.2-preview</MetalamaPremiumVersion>
    <MetalamaSamplesVersion Condition="'$(MetalamaSamplesVersion)' == ''">2027.0.2-preview</MetalamaSamplesVersion>
    <MetalamaDocumentationReleaseVersion>2027.0.2-preview</MetalamaDocumentationReleaseVersion>
    <MetalamaDocumentationReleaseMainVersion>2027.0.2</MetalamaDocumentationReleaseMainVersion>
  </PropertyGroup>
</Project>